use resona_core::*;
use ts_rs::TS;
fn main() {
    let declarations = [
        Settings::decl(),
        Turn::decl(),
        SourceStatus::decl(),
        Bootstrap::decl(),
        Filters::decl(),
        Summary::decl(),
        ModelSummary::decl(),
        DistributionBin::decl(),
        TrendBucket::decl(),
        Dashboard::decl(),
        ListRequest::decl(),
        TurnPage::decl(),
    ];
    let text = format!(
        "// Generated by cargo run -p resona-core --example export_types. Do not edit.\n{}\n",
        declarations
            .into_iter()
            .map(|s| format!("export {s}"))
            .collect::<Vec<_>>()
            .join("\n")
    );
    print!("{text}");
}
