// Generated by cargo run -p resona-core --example export_types. Do not edit.
export type Settings = {
  revision: number;
  launchAtLogin: boolean;
  menuMetric: string;
  showProvider: boolean;
  showModel: boolean;
  theme: string;
  defaultRange: string;
  codexHome: string;
  claudeProjects: string;
  codexEnabled: boolean;
  claudeEnabled: boolean;
};
export type Turn = {
  provider: string;
  turnKey: string;
  nativeTurnId: string;
  ownerThreadId: string | null;
  model: string | null;
  status: string;
  threadKind: string;
  identityStatus: string;
  recordSource: string;
  startedAtMs: number | null;
  completedAtMs: number | null;
  firstAssistantAtMs: number | null;
  durationMs: number | null;
  ttftMs: number | null;
  ttftSource: string;
  outputTokens: number | null;
  tokenSource: string;
  tps: number | null;
  hasTool: boolean;
  qualityCode: string | null;
};
export type SourceStatus = {
  provider: string;
  kind: string;
  path: string;
  enabled: boolean;
  state: string;
  files: number;
  errorFiles: number;
  lastSuccessAtMs: number | null;
};
export type Bootstrap = {
  settings: Settings;
  storageDirectory: string;
  sources: Array<SourceStatus>;
  dataRevision: number;
  scanning: boolean;
  recent: Array<Turn>;
  active: Array<Turn>;
  version: string;
  error: string | null;
};
export type Filters = {
  range: string;
  providers: Array<string>;
  model?: string | null;
  startDate?: string | null;
  endDate?: string | null;
};
export type Summary = {
  completedCount: number;
  ttftValidCount: number;
  tpsValidCount: number;
  excludedCount: number;
  ttftP50: number | null;
  ttftP95: number | null;
  tpsP50: number | null;
  tpsP5: number | null;
  codexCount: number;
  claudeCount: number;
};
export type ModelSummary = { provider: string; model: string | null; summary: Summary };
export type DistributionBin = {
  lower: number;
  upper: number;
  codexCount: number;
  claudeCount: number;
};
export type TrendBucket = {
  startAtMs: number;
  endExclusiveMs: number;
  provider: string;
  summary: Summary;
};
export type Dashboard = {
  dataRevision: number;
  asOfMs: number;
  startAtMs: number | null;
  endExclusiveMs: number;
  summary: Summary;
  models: Array<ModelSummary>;
  points: Array<Turn>;
  totalPoints: number;
  ttftBins: Array<DistributionBin>;
  tpsBins: Array<DistributionBin>;
  trendBuckets: Array<TrendBucket>;
  sources: Array<SourceStatus>;
  scanning: boolean;
};
export type ListRequest = {
  filters: Filters;
  status: string | null;
  search: string | null;
  sort: string;
  pageSize: number;
  cursor: string | null;
};
export type TurnPage = {
  dataRevision: number;
  total: number;
  items: Array<Turn>;
  nextCursor: string | null;
};
